### ISSUE TITLE
ModuleNotFoundError: No module named 'giscanner._giscanner'

### ISSUE THREAD

**Issue by SuperSecureHuman** [AyatanaIndicators/ayatana-ido#56]
Hey there
I have installed all the dependencies mentioned in the install page, yet I get this error

![2021-12-27_14-19](https://user-images.githubusercontent.com/88489071/147453812-2a5e3997-9e70-4563-9a9a-ecac59ecf60f.png)

I am on arch linux

**Comment by tari01** [comment]
@SuperSecureHuman

This seems to be a `gobject-introspection` issue. Could you please check that your `gobject-introspection` python files have all been migrated to 3.10?

**Comment by SuperSecureHuman** [comment]
I am on python python 3.9
and I installed gobject-introspection via pacman (https://archlinux.org/packages/extra/x86_64/gobject-introspection/)
I did not manually do anything else :thinking:

**Comment by tari01** [comment]
> I am on python python 3.9 

That's a little weird, Arch should now be at 3.10

> and I installed gobject-introspection via pacman (https://archlinux.org/packages/extra/x86_64/gobject-introspection/) I did not manually do anything else

You can check if your python paths for your `gobject-introspection` installation work by opening a terminal and simply entering:

` g-ir-scanner`

You should get:

`ERROR: Need at least one filename`

**Comment by SuperSecureHuman** [comment]
Ahh yes
Found my issue
It was conda
the gobject-introspection was installed for the system python
I had to deactivate conda for it to work :facepalm: 

You can close this issue, if u dont have any comments on this

**Comment by tari01** [comment]
Closing, issue was unrelated to ayatana-ido.
